### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by K-945** [wisdom-pan/datawhale_aigcTask#1]
<img width="709" alt="屏幕截图 2023-05-21 175957" src="https://github.com/wisdom-pan/datawhale_aigcTask/assets/48827771/bbce9f3e-d4e6-41df-b140-2a8cee4eb6d2">

佬，执行python main.py时候出现了这个问题，该怎么解决呢？

**Comment by wisdom-pan** [comment]
收到

**Comment by wisdom-pan** [comment]
需要设置一个openai的key，可以通过环境变量设置或者在yaml文件里面指定，这个是没有key导致的报错

**Comment by K-945** [comment]
不行呀，我这个之前在yaml里添加了，刚才给系统里也添加了还是一样的报错

**Comment by wisdom-pan** [comment]
噢噢，我看代码里我把这个注释掉了，你用添加环境变量的方式添加OPENAI_API_KEY吧
